apiVersion: trustedservices.intel.com/v1
kind: TdxQuoteGenerationService
metadata:
  name: intel-tdx-dcap
  namespace: intel-dcap
spec:
  nodeSelector:
    - "intel.feature.node.kubernetes.io/tdx=true"
  platformRegistration:
    Offline: {}
