apiVersion: confidentialcontainers.org/v1alpha1
kind: KbsConfig
metadata:
  name: kbsconfig
  namespace: trustee-operator-system
spec:
  kbsConfigMapName: kbs-config-cm
  kbsAuthSecretName: kbs-auth-public-key
  kbsAttestationKeySecretName: kbs-attestation-key
  kbsAttestationCertSecretName: kbs-attestation-cert
  kbsDeploymentType: AllInOneDeployment
