apiVersion: v1
kind: ConfigMap
metadata:
  name: osc-feature-gates
  namespace: openshift-sandboxed-containers-operator
data:
  confidential: '{{hub index .ManagedClusterLabels "autoshift.io/sandboxed-containers-confidential" | default "true" hub}}'
  deploymentMode: DaemonSetFallback
