apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../../../components/
helmCharts:
  - name: operator-install
    releaseName: intel-device-plugins
    valuesInline:
      name: intel-device-plugins
      namespace: openshift-operators
      targetNamespaces: []
      remediation: ${REMEDIATION}
      subscription:
        name: '{{hub index .ManagedClusterLabels "autoshift.io/intel-device-plugins-subscription-name" | default "intel-device-plugins-operator" hub}}'
        channel: '{{hub index .ManagedClusterLabels "autoshift.io/intel-device-plugins-channel" | default "stable" hub}}'
        source: '{{hub $base := (index .ManagedClusterLabels "autoshift.io/intel-device-plugins-source" | default "certified-operators") hub}}{{hub ternary (printf "%s-%s" $base (index .ManagedClusterLabels "autoshift.io/mirror-catalog-suffix" | default "mirror")) $base (eq (index .ManagedClusterLabels "autoshift.io/disconnected-mirror" | default "false") "true") hub}}'
        sourceNamespace: '{{hub index .ManagedClusterLabels "autoshift.io/intel-device-plugins-source-namespace" | default "openshift-marketplace" hub}}'
        startingCSV: |-
          {{hub- $cfg := (index (index (index ((lookup "v1" "ConfigMap" .PolicyMetadata.namespace (printf "%s.rendered-config" .ManagedClusterName)) | default dict) "data" | default dict) "config" | default "" | fromYaml | default dict) "intel-device-plugins" | default dict) hub}}
          {{hub- $cfgVers := (dig "versions" (list) $cfg) hub}}
          {{hub- $isCfg := (not (empty $cfgVers)) hub}}
          {{hub- $labelVer := (index .ManagedClusterLabels "autoshift.io/intel-device-plugins-version" | default "") hub}}
          {{hub- $vers := (ternary $cfgVers (ternary (list) (list $labelVer) (empty $labelVer)) $isCfg) hub}}
          {{hub- (ternary (dig "startingCSV" "" $cfg) $labelVer $isCfg) hub}}
      versions: '{{hub $vers | toRawJson | toLiteral hub}}'
