apiVersion: deviceplugin.intel.com/v1
kind: SgxDevicePlugin
metadata:
  name: sgx-device-plugin
  namespace: openshift-operators
spec:
  image: ""
  enclaveLimit: 10
  provisionLimit: 10
  nodeSelector:
    intel.feature.node.kubernetes.io/sgx: 'true'
