apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: nvme-localvolumeset
  namespace: openshift-local-storage
spec:
  deviceInclusionSpec:
    deviceTypes:
    - disk
    minSize: 200G
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: cluster.ocs.openshift.io/openshift-storage
        operator: Exists
  storageClassName: nvme-storageclass
  tolerations:
  - effect: NoSchedule
    key: node.ocs.openshift.io/storage
    operator: Exists
  volumeMode: Block
